### ISSUE TITLE
Скорость работы и размер бд

### ISSUE THREAD

**Issue by ShukinDmitriy** [asyncee/fias2pgsql#11]
Добрый день! подскажите сколько времени занимает полный парсинг с 0 и сколько места занимает конечная бд. также интересует наличие партиций в таблицах. Спасибо

**Comment by asyncee** [comment]
Проект поддерживается сообществом, возможно @xlazex @Hedgehogues @Wrussia помогут с ответом.

**Comment by Eugene-Kei** [comment]
Вчера скачал полную базу фиас, на сайте налоговой, сделал все шаги указанные в readme.md. 
DBeaver показывает размер всех талиц 18 гб.
