### ISSUE TITLE
Релиз 1.0

### ISSUE THREAD

**Issue by Hedgehogues** [asyncee/fias2pgsql#4]
Я предлагаю следующее в связи с тем, что у меня есть правки относительно путей внутри скриптов:

1. Синхронизировать develop и master
2. Я делаю pull request с моими правками
3. Мы делаем релиз 1.0.0, так как я не могу оценить: есть ли сейчас обратная совместимость или нет
4. Я также предлагаю делать все изменения в develop, а релизы связывать с веткой master

**Comment by asyncee** [comment]
По всем пунктам согласен. Что конкретно имеется ввиду под релизом? Теги на бранчи, installable package из pypi или просто релизы, созданные посредством гитхаба (вкладка release)?

**Comment by asyncee** [comment]
Добавил ветку develop и сделал release через github.
