### ISSUE TITLE
Относительный путь в import.sh, хотя в параметрах используется полный

### ISSUE THREAD

**Issue by valunok** [asyncee/fias2pgsql#6]
https://github.com/asyncee/fias2pgsql/blob/51394e3adec27cce9eb401f0ea07aec25eef9969/import.sh#L11

**Comment by asyncee** [comment]
Привет! Сейчас скрипт поддерживается сообществом, последние изменения были внесены в ветку develop, в том числе и исправление этой проблемы. Я выложил эти изменения в master. Исправило ли это проблему?

**Comment by valunok** [comment]
Привет! Нет, не исправило. Если честно, не понимаю зачем было делать это:
https://github.com/asyncee/fias2pgsql/blob/7801c4518796b3a84c024e9d9ded0acb566b35ac/import.sh#L4
Мне кажется было лучше.

**Comment by asyncee** [comment]
Эти изменения были предложены в одном из последних PR. Так как я проект не поддерживаю и не могу протестировать, а изменения в коде выглядели логично, то было принято решение влить их в проект.

И да, согласен, explicit is better than implicit и вариант с `PATH_TO_DBF_FILES` более понятный и читаемый.

Обновил README в master для отображения текущей ситуации с PR.

Буду благодарен, если вы сделаете новый PR для исправления этой проблемы в актуальной версии проекта.

**Comment by asyncee** [comment]
Спасибо за исправление.
